### ISSUE TITLE
Frontend - Create a workers card  Head and Bottom from home page 

### ISSUE THREAD

**Issue by paulowiz** [cafemaismais/workerspanelcafemm#1]
Create a workers card with this information:

- Photo 
- Name 
- City, District, and Country 
- Link of ( Linkedin, GitHub, blog) 

Menu - Could be a simple menu with Home, Map, and Contact. 

Bottom - You can use your creativity and will have information about Cafemaismais.

Reference: https://zero-to-mastery.github.io/ZtM-Job-Board/

You are free to use anything pretty on page =)

**Comment by faizaslam11** [comment]
Okay! Thanks for the Task :)

**Comment by paulowiz** [comment]
> Okay! Thanks for the Task :)

Look at this model https://html5up.net/

**Comment by faizaslam11** [comment]
![Uploading 2021-01-26 (1).png…]()
