### ISSUE TITLE
Frontend - Create a map with how many workers are there in coffee++

### ISSUE THREAD

**Issue by paulowiz** [cafemaismais/workerspanelcafemm#2]
Create a map component that will receive a JSON with country and total and set on the map the marks.

**Comment by Suspir0n** [comment]
@faizaslam11 @paulowiz  Do you know any public API for maps ?

**Comment by paulowiz** [comment]
> @faizaslam11 @paulowiz Do you know any public API for maps ?

You can use this public API for maps https://wiki.openstreetmap.org/wiki/API_v0.6

**Comment by paulowiz** [comment]
https://html5up.net/

**Comment by Suspir0n** [comment]
Map creation showing the location of several developers finish.
The only problem is use external JSON file, error of read from file.

**Comment by Suspir0n** [comment]
any suggestion ??
