### ISSUE TITLE
Frontend - Registration page 

### ISSUE THREAD

**Issue by paulowiz** [cafemaismais/workerspanelcafemm#5]
We need a registration page that will have:

- Name ( Jonh Welly )
- City, State, and Country ( Ex: Belo Horizonte, Minas Gerais, Brazil )
- Title ( Ex: React Developer )
- Link Github
- Link LinkedIn
- Link webpage

**Comment by paulowiz** [comment]
http://www.mashup-template.com/templates.html

**Comment by thalesantana** [comment]
https://unsplash.com/s/photos/developer

**Comment by thalesantana** [comment]
https://source.unsplash.com/
https://unsplash.com/s/photos/the-source
